#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME, XARGS.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g -x README.md -x patches -x install -x LICENSE
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
: ${XARGS:=/usr/bin/xargs}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/bbennett37/.dotfiles/bin/add_reminder" "/home/bbennett37/.bin/add_reminder"
handle_file_ln "/home/bbennett37/.dotfiles/bin/check_mail" "/home/bbennett37/.bin/check_mail"
handle_file_ln "/home/bbennett37/.dotfiles/bin/dmenu_path" "/home/bbennett37/.bin/dmenu_path"
handle_file_ln "/home/bbennett37/.dotfiles/bin/gist" "/home/bbennett37/.bin/gist"
handle_file_ln "/home/bbennett37/.dotfiles/bin/git" "/home/bbennett37/.bin/git"
handle_file_ln "/home/bbennett37/.dotfiles/bin/lock_screen" "/home/bbennett37/.bin/lock_screen"
handle_file_ln "/home/bbennett37/.dotfiles/bin/mediactl" "/home/bbennett37/.bin/mediactl"
handle_file_ln "/home/bbennett37/.dotfiles/bin/notmuch_sendmail" "/home/bbennett37/.bin/notmuch_sendmail"
handle_file_ln "/home/bbennett37/.dotfiles/bin/openup" "/home/bbennett37/.bin/openup"
handle_file_ln "/home/bbennett37/.dotfiles/bin/push_file_from_directory" "/home/bbennett37/.bin/push_file_from_directory"
handle_file_ln "/home/bbennett37/.dotfiles/bin/slmenu_run" "/home/bbennett37/.bin/slmenu_run"
handle_file_ln "/home/bbennett37/.dotfiles/bin/snippet" "/home/bbennett37/.bin/snippet"
handle_file_ln "/home/bbennett37/.dotfiles/bin/stat_line" "/home/bbennett37/.bin/stat_line"
handle_file_ln "/home/bbennett37/.dotfiles/bin/watch_sgdq" "/home/bbennett37/.bin/watch_sgdq"
handle_file_ln "/home/bbennett37/.dotfiles/emacs.d/custom.el" "/home/bbennett37/.emacs.d/custom.el"
handle_file_ln "/home/bbennett37/.dotfiles/emacs.d/init.el" "/home/bbennett37/.emacs.d/init.el"
handle_file_ln "/home/bbennett37/.dotfiles/emacs.d/keymap.el" "/home/bbennett37/.emacs.d/keymap.el"
handle_file_ln "/home/bbennett37/.dotfiles/emacs.d/languages.el" "/home/bbennett37/.emacs.d/languages.el"
handle_file_ln "/home/bbennett37/.dotfiles/emacs.d/packages.el" "/home/bbennett37/.emacs.d/packages.el"
handle_file_ln "/home/bbennett37/.dotfiles/emacs.d/ui.el" "/home/bbennett37/.emacs.d/ui.el"
handle_file_ln "/home/bbennett37/.dotfiles/gitconfig" "/home/bbennett37/.gitconfig"
handle_file_ln "/home/bbennett37/.dotfiles/gitignore" "/home/bbennett37/.gitignore"
handle_file_ln "/home/bbennett37/.dotfiles/install_arch.sh" "/home/bbennett37/.install_arch.sh"
handle_file_ln "/home/bbennett37/.dotfiles/install.conf.yaml" "/home/bbennett37/.install.conf.yaml"
handle_file_ln "/home/bbennett37/.dotfiles/mutt/keysrc" "/home/bbennett37/.mutt/keysrc"
handle_file_ln "/home/bbennett37/.dotfiles/mutt/muttrc" "/home/bbennett37/.mutt/muttrc"
handle_file_ln "/home/bbennett37/.dotfiles/mutt/themerc" "/home/bbennett37/.mutt/themerc"
handle_file_ln "/home/bbennett37/.dotfiles/pythonrc" "/home/bbennett37/.pythonrc"
handle_file_ln "/home/bbennett37/.dotfiles/tmux.conf" "/home/bbennett37/.tmux.conf"
handle_file_ln "/home/bbennett37/.dotfiles/tmux.session.work" "/home/bbennett37/.tmux.session.work"
handle_file_ln "/home/bbennett37/.dotfiles/xinitrc" "/home/bbennett37/.xinitrc"
handle_file_ln "/home/bbennett37/.dotfiles/zaliases" "/home/bbennett37/.zaliases"
handle_file_ln "/home/bbennett37/.dotfiles/zprofile" "/home/bbennett37/.zprofile"
handle_file_ln "/home/bbennett37/.dotfiles/zshenv" "/home/bbennett37/.zshenv"
handle_file_ln "/home/bbennett37/.dotfiles/zshrc" "/home/bbennett37/.zshrc"
