#! /usr/bin/env python
from __future__ import print_function

from glob import glob
from os import path, symlink, unlink
from shutil import rmtree


def get_files():
    return [file for file in glob("*")]


def run(files):
    excluded = parse_excludes()
    print("Excluding: {}".format(", ".join(excluded)))
    for file in files:
        if file not in excluded:
            home_path = path.expanduser("~/." + file)
            abs_path = path.abspath(file)
            print(path.abspath(file) + " -> " + home_path)
            if path.isfile(home_path) or path.islink(home_path):
                # our file is a file/link in $HOME. Unlink / Relink.
                unlink(home_path)
                symlink(abs_path, home_path)
            elif path.isdir(home_path):
                # our file is a directory in $HOME. delete folder and symlink.
                rmtree(home_path)
                symlink(abs_path, home_path)
            else:
                # our file is not in $HOME at all. Blindly link.
                symlink(abs_path, home_path)


def parse_excludes():
    with open("excluded", 'r') as f:
        ex = [line.strip() for line in f]
    return tuple(ex)

if __name__ == "__main__":
    files = get_files()
    run(files)
    pass
