(eval-after-load "flycheck" '(diminish 'flycheck-mode ""))
(eval-after-load "hideshow" '(diminish 'hs-minor-mode "h"))
(eval-after-load "undo-tree" '(diminish 'undo-tree-mode ""))
(eval-after-load "projectile" '(diminish 'projectile-mode ""))
(eval-after-load "company" '(diminish 'company-mode ""))
(eval-after-load "grizzl" '(diminish 'company-mode ""))
(eval-after-load "anaconda" '(diminish 'anaconda-mode ""))
(eval-after-load "outline" '(diminish 'outline-mode ""))
